sudo: required
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
script:
    - chmod +x gradlew
    - ./gradlew assembleDebug

deploy:
  provider: releases
  file: openmrs-client/build/outputs/apk/openmrs-client-release.apk
  skip_cleanup: true
  on:
    tags: false
    all_branches: true